services:
  - type: web
    name: clasificador-residuos-backend
    runtime: docker
    rootDir: backend
    dockerfilePath: ./Dockerfile
    plan: free
    healthCheckPath: /health
    autoDeploy: true

  - type: web
    name: clasificador-residuos-frontend
    runtime: static
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .
    autoDeploy: true
